# Generated by Django 5.1.1 on 2024-09-23 08:54

import django_ckeditors.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=40)),
                ('header_description', django_ckeditors.fields.CKEditorsField(blank=True, null=True)),
                ('header_image', models.ImageField(upload_to='header')),
            ],
        ),
    ]
