# Generated by Django 5.1.1 on 2024-09-24 08:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_intro', models.CharField(max_length=200)),
                ('about_image_content', models.ImageField(upload_to='about')),
                ('about_header', models.CharField(max_length=100)),
                ('about_content', django_ckeditor_5.fields.CKEditor5Field()),
                ('about_story', models.CharField(max_length=100)),
                ('about_story_detail', models.CharField(max_length=200)),
                ('about_image_story', models.ImageField(upload_to='about')),
                ('about_goal', models.CharField(max_length=100)),
                ('about_goal_detail', models.CharField(max_length=200)),
                ('about_image_goal', models.ImageField(upload_to='about')),
            ],
        ),
    ]
