# Generated by Django 5.1.1 on 2024-09-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_image',
            field=models.ImageField(upload_to='header'),
        ),
    ]
