# Generated by Django 5.1.1 on 2024-09-23 05:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_header_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
